### ISSUE TITLE
Move npm module to esm and drop node < 20

### ISSUE THREAD

**Issue by polRk** [hyperledger/fabric-protos#224]

**Comment by bestbeforetoday** [comment]
Node 18 is still a supported [LTS release](https://github.com/nodejs/release#release-schedule) for another year. We should definitely **not** drop support for it before it reaches end-of-life.

**Comment by bestbeforetoday** [comment]
Provided it doesn't cause any compatibility issues for existing Node users, ensuring the [@hyperledger/fabric-protos](https://www.npmjs.com/package/@hyperledger/fabric-protos) package is an ES module rather than CommonJS sounds pretty reasonable to me. I'm not sure how well the protobuf compiler output lends itself to being exposed as an ES module directly or if it relies on CommonJS import/export semantics. Maybe a bundler could be used to achieve the desired result?

**Comment by polRk** [comment]
> Node 18 is still a supported [LTS release](https://github.com/nodejs/release#release-schedule) for another year. We should definitely **not** drop support for it before it reaches end-of-life.

But now u support node 14...

**Comment by polRk** [comment]
> Maybe a bundler could be used to achieve the desired result?

Yes, the current compiler is disgusting, you need to write a new solution here...

**Comment by bestbeforetoday** [comment]
If you have a good idea for a better approach, you could submit a pull request?

**Comment by bestbeforetoday** [comment]
Hmmm, digging a bit more into ESM and CommonJS module loading... it _seems_ that ES modules can load CommonJS modules fine (with some minor caveats related to default exports), whereas ComonJS modules cannot (easily) load ES modules. Today fabric-protos is a CommonJS module so can be used by both CommonJS and ES modules. If we change fabric-protos to be a native ES module, it will break all existing CommonJS applications that depend on fabric-protos. That doesn't sound like a great change, although I'm happy to hear from anyone with better information.
